version: '3.9'
services:

  server:
    image: server
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - "8022:8022"
    environment:
      - APP_ENV=local
      - APP_DSN=postgresql://localhost/postgres?sslmode=disable&user=postgres&password=postgres
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: "postgres:alpine"
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - host
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure