app:
  name: sample-app.com
  port: 8022

jwt:
  access_signing_key: E4IiEcW02N4N2HKWnUjA6KxwrrrJME4SrO2FHDN0CDhHUfqjDmIiAlIoXMnG9brY
  access_expiration: 5
  refresh_signing_key: KQciMyZms5nBhiEwABX9srXPVCR9PFnka3Ci3SseB4XAjBU4OTVIj1jat5oLvhCv
  refresh_expiration: 10080

dsn: "postgresql://db/postgres?sslmode=disable&user=postgres&password=postgres"

redis:
  host: "redis"
  port: 6379
  password: testing
  db: 0
  pool_size: 500