app:
  name: sample-app.com
  port: 50051
  cert: "./testdata/x509/cert.pem"
  key: "./testdata/x509/key.pem"

context:
  timeout: 2

jwt:
  access_signing_key: E4IiEcW02N4N2HKWnUjA6KxwrrrJME4SrO2FHDN0CDhHUfqjDmIiAlIoXMnG9brY
  access_expiration: 5
  refresh_signing_key: KQciMyZms5nBhiEwABX9srXPVCR9PFnka3Ci3SseB4XAjBU4OTVIj1jat5oLvhCv
  refresh_expiration: 10080

dsn: "postgresql://localhost/postgres?sslmode=disable&user=postgres&password=postgres"

redis:
  host: "127.0.0.1"
  port: 6379
  password: redis
  db: 0
  pool_size: 500
