app:
  name: app
  port: 8022

jwt:
  access_jwt_signing_key: E4IiEcW02N4N2HKWnUjA6KxwrrrJME4SrO2FHDN0CDhHUfqjDmIiAlIoXMnG9brY
  access_jwt_expiration: 5
  refresh_jwt_signing_key: KQciMyZms5nBhiEwABX9srXPVCR9PFnka3Ci3SseB4XAjBU4OTVIj1jat5oLvhCv
  refresh_jwt_expiration: 10080

db:
  host: "127.0.0.1"
  port: 5432
  user: docker
  password: docker
  dbname: docker

redis:
  host: "127.0.0.1"
  port: 6379
  password: redis
  db: 0
  pool_size: 500