app:
  name: app
  port: 8022

jwt:
  access_signing_key: E4IiEcW02N4N2HKWnUjA6KxwrrrJME4SrO2FHDN0CDhHUfqjDmIiAlIoXMnG9brY
  access_expiration: 5
  refresh_signing_key: KQciMyZms5nBhiEwABX9srXPVCR9PFnka3Ci3SseB4XAjBU4OTVIj1jat5oLvhCv
  refresh_expiration: 10080

db:
  host: "127.0.0.1"
  port: 5432
  user: alex
  password: testing
  dbname: postgres

redis:
  host: "127.0.0.1"
  port: 6379
  password: testing
  db: 0
  pool_size: 500