package log

import (
	"context"
	"os"
	"time"

	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"go.uber.org/zap/zaptest/observer"
	"gopkg.in/natefinch/lumberjack.v2"
)

type LogType string

const (
	AccessLog LogType = "access"
	ApiLog    LogType = "api"

	localPath = "./"
	devPath   = "/www/wwwlog/"
	prodPath  = "/www/wwwlog/"

	apiFileName  = "api.log"
	apiMaxSize   = 2
	apiMaxBackup = 3
	apiMaxAge    = 3

	accessFileName  = "access.log"
	accessMaxSize   = 2
	accessMaxBackup = 3
	accessMaxAge    = 3
)

// Logger is a logger that supports log levels, context and structured logging.
type Logger interface {
	// With returns a logger based off the root logger and decorates it with the given context and arguments.
	With(ctx context.Context, args ...interface{}) Logger

	// Debug uses fmt.Sprint to construct and log a message at DEBUG level
	Debug(args ...interface{})
	// Info uses fmt.Sprint to construct and log a message at INFO level
	Info(args ...interface{})
	// Error uses fmt.Sprint to construct and log a message at WARN level
	Warn(args ...interface{})
	// Error uses fmt.Sprint to construct and log a message at ERROR level
	Error(args ...interface{})
	// Error uses fmt.Sprint to construct and log a message at WARN level
	Fatal(args ...interface{})

	// Debugf uses fmt.Sprintf to construct and log a message at DEBUG level
	Debugf(format string, args ...interface{})
	// Infof uses fmt.Sprintf to construct and log a message at INFO level
	Infof(format string, args ...interface{})
	// Errorf uses fmt.Sprintf to construct and log a message at WARN level
	Warnf(format string, args ...interface{})
	// Errorf uses fmt.Sprintf to construct and log a message at ERROR level
	Errorf(format string, args ...interface{})
	// Errorf uses fmt.Sprintf to construct and log a message at WARN level
	Fatalf(format string, args ...interface{})
}

type logger struct {
	*zap.SugaredLogger
}

// New creates a new logger
func New(env string, log LogType) Logger {
	c := new(zapcore.Core)

	if env == "local" {
		*c = zapcore.NewTee(zapcore.NewCore(encoder(env), zapcore.Lock(os.Stdout), zap.InfoLevel))
	} else {
		var level zapcore.Level
		var writeSyncer zapcore.WriteSyncer
		var path string

		switch env {
		case "local":
			path = localPath
		case "dev":
			path = devPath
		case "qa":
			path = devPath
		case "prod":
			path = prodPath
		}

		if log == AccessLog {
			level = zap.InfoLevel
			writeSyncer = newWriteSyncer(path+accessFileName, accessMaxSize, accessMaxBackup, accessMaxAge)
		} else {
			level = zap.ErrorLevel
			writeSyncer = newWriteSyncer(path+apiFileName, apiMaxSize, apiMaxBackup, apiMaxAge)
		}

		*c = zapcore.NewTee(zapcore.NewCore(encoder(env), writeSyncer, level))
	}

	l := zap.New(*c, zap.AddCaller(), zap.AddCallerSkip(0))

	return NewWithZap(l)
}

// Customize log encoder
func encoder(mode string) zapcore.Encoder {
	encoderConfig := zap.NewProductionEncoderConfig()
	encoderConfig.EncodeLevel = zapcore.CapitalLevelEncoder
	encoderConfig.TimeKey = "time"
	encoderConfig.EncodeTime = func(t time.Time, enc zapcore.PrimitiveArrayEncoder) {
		enc.AppendString(t.Local().Format("2006-01-02T15:04:05Z0700"))
	}
	if mode == "local" {
		encoderConfig.EncodeLevel = zapcore.CapitalColorLevelEncoder
		return zapcore.NewConsoleEncoder(encoderConfig)
	}
	return zapcore.NewJSONEncoder(encoderConfig)
}

func newWriteSyncer(fileName string, maxSize, maxBackup, maxAge int) zapcore.WriteSyncer {
	lumberJackLogger := &lumberjack.Logger{
		Filename:   fileName,
		MaxSize:    maxSize,
		MaxBackups: maxBackup,
		MaxAge:     maxAge,
	}
	return zapcore.AddSync(lumberJackLogger)
}

// NewWithZap creates a new logger using the preconfigured zap logger.
func NewWithZap(l *zap.Logger) Logger {
	return &logger{l.Sugar()}
}

// NewForTest returns a new logger and the corresponding observed logs which can be used in unit tests to verify log entries.
func newForTest() (Logger, *observer.ObservedLogs) {
	core, recorded := observer.New(zapcore.InfoLevel)
	return NewWithZap(zap.New(core)), recorded
}

// With returns a logger based off the root logger and decorates it with the given context and arguments.
//
// The arguments should be specified as a sequence of name, value pairs with names being strings.
// The arguments will also be added to every log message generated by the logger.
func (l *logger) With(ctx context.Context, args ...interface{}) Logger {
	if len(args) > 0 {
		return &logger{l.SugaredLogger.With(args...)}
	}
	return l
}
